.TH usm 1 "23 February 2013" "Version 1.11" "USM LIBRARY HELPER"
.SH NAME
.B usm-lib-helper
\- The USM Library Helper
.SH SYNOPSIS
.B usm-lib-helper
<name>
[program]
.SH DESCRIPTION
This is a utility for running programs under USM that depend upon shared objects.
.PP
When the loader looks for a shared library, it will look by default in the
system library directories.
This program adds the program directory matched by
.B name
(which can be a glob - but the program automatically adds a star to the end)
to the loader library path to allow the loader to find the shared objects in
the USM.
.SH OPTIONS
.TP
name
The program directory to set the loader path to. This is automatically
globbed with a star at the end, but other globs can be used as well.
.TP program
The command line to run after setting the loader path. If empty, usm-lib-helper runs a bash shell with the correct loader set for the shell's lifetime.
.SH AUTHOR
adamnew123456 <adamnew123456@gmail.com> and on GitHub
.SH SEE ALSO
This utility is a part of usm(1)
